### ISSUE TITLE
Create universal binary

### ISSUE THREAD

**Issue by mattbisme** [Rexios80/hds_desktop#1]
Looks like the binary is Intel only. Without Rosetta installed, I'm getting this error in Terminal:

```
zsh: bad CPU type in executable
```

Running macOS Sonoma 14.2.1. After installing Rosetta, this issues goes away. However, it was not an obvious fix (I just happen to think of it when I was prompted by an unrelated app). If possible, a universal build would be great. Otherwise, something to prompt the user to install Rosetta would be a workaround.

**Comment by Rexios80** [comment]
I believe building a universal binary would require compiling on Apple Silicon which normal GitHub Actions runners don't currently support

**Comment by mattbisme** [comment]
If you want to provide the compile instructions, I might be able to give it a go.

**Comment by Rexios80** [comment]
Look up how to install Dart first. Then:

`dart compile exe bin/hds_desktop.dart -o hds_desktop_macos`

**Comment by mattbisme** [comment]
```
% file hds_desktop_macos 
hds_desktop_macos: Mach-O 64-bit executable arm64
```

Never used Dart before, but once I figured out how to install dependencies, the rest was easy:
[Here is an arm64 binary](https://github.com/Rexios80/hds_desktop/files/13804224/hds_desktop_macos.zip)

If there is another command that would produce a universal version, I'm happy to try that too. I think separate Intel/arm64 versions is fine. But, I'll leave it to you to decide if this issue should be closed.

Let me know if you want me to compile future versions as well.

**Comment by Rexios80** [comment]
I'm leaving this as is until GitHub Actions supports building on Apple Silicon. I think what we would have to do is build for both architectures and combine them.

**Comment by Rexios80** [comment]
I didn't end up creating a universal binary, but I did get a runner working for Apple Silicon so now there is both an Intel and Apple Silicon version

**Comment by mattbisme** [comment]
Nice! I'll try to give it a go this Friday. Thanks!
